### PR TITLE
chore: bump expo version

### PR DESCRIPTION
**Pull request by rolznz**
Expo Go has released a new version, which requires us to update (at least on iOS).

There seem to be some bugs with the change. For some reason, the webview crypto polyfill seems to not be working (NWC requests do not work)

### CODE REVIEW

**Comment by rolznz** [comment]
Either we need message-port-polyfill or https://github.com/nbd-wtf/nostr-tools/compare/master...rolznz:fix/yield-thread-react-native?expand=1 

But this requires us to update the JS SDK to use nostr-tools 2.x first. https://github.com/getAlby/js-sdk/pull/275 and we should update lightning-tools too.

**Comment by rolznz** [comment]
Update: adding `"message-port-polyfill": "^0.2.0",`

And calling `import "message-port-polyfill";` from `applyGlobalPolyfills` is enough. `applyGlobalPolyfills` might need to be imported before the expo entry point (TBC)

**Comment by rolznz** [comment]
Edit: it looks like the crypto webview polyfill is still needed.

**Comment by im-adithya** [comment]
Changed the splash background color to mask the difference

## Before and After
<table>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

**Review by im-adithya — APPROVED** [review]
tACK

**Pull request merged**
