### PR TITLE
doc: add instructions on how to connect Alby Go with Alby Hub

### PR DESCRIPTION
**Pull request by kennym**
Updates `README.md` on how to connect Alby Go with your Alby Hub.

Context: when I first downloaded Alby Go from TestFlight it was not clear to me what QR code to scan.

### CODE REVIEW

**Comment by matjaz** [comment]
Maybe there should be mention of NWC, so any NWC node can be used.

**Comment by reneaaron** [comment]
> Context: when I first downloaded Alby Go from TestFlight it was not clear to me what QR code to scan.

Now that we have this info added to the app itself (there is a help icon on the scan screen that explains how to connect) do you think we still need it in the README?

**Comment by kennym** [comment]
> Now that we have this info added to the app itself (there is a help icon on the scan screen that explains how to connect) do you think we still need it in the README?

No, closing this. In any case, the README could use some general love <3

Thanks!

**Comment by rolznz** [comment]
@kennym what sort of stuff would you add to the README that would provide value for developers? we will probably add a landing page later which can show screenshots and describe the product in more detail.

**Comment by rolznz** [comment]
https://github.com/getAlby/go/pull/115

**Pull request closed without merging**
