### PR TITLE
chore: add high error correction level to qr codes

### PR DESCRIPTION
**Pull request by im-adithya**
## Description

This makes QR codes more reliable across different scanners. [More info](https://www.qrcode-tiger.com/qr-code-error-correction)

## Screenshots

<table>
<tr>
<td>

</td>
<td>

</td>

<td>

</td>
<td>

</td>
</tr>

</table>

### CODE REVIEW

**Comment by rolznz** [comment]
@im-adithya is it still good to do this for regular invoices? the QR code is super detailed now. What about only for lightning addresses?

**Comment by im-adithya** [comment]
Yeah I had the same thought, but we want to have the Go icon as well in there so I added `ecl="H"` We can
- Either remove the icon for invoices
- Or keep the icon and maybe reduce error correction to `"M"` or `"Q"`

**Review by rolznz — APPROVED** [review]
utACK

**Comment by im-adithya** [comment]
Merging this for now, shouldn't be an issue apart from how it looks

**Pull request merged**
